### ISSUE TITLE
Release 2.0.0 checklist

### ISSUE THREAD

**Issue by lbguilherme** [sdkgen/sdkgen#169]
- [ ] Drop `get` and `function` syntax
 - [ ] Drop `api.hooks` in favor of middlewares
 - [ ] Drop `api.err` in favor of creating the exception directly
 - [ ] Add `useContext()` and stop passing `ctx` argument
 - [x] Replace `Buffer` with `ArrayBuffer` on browser target (https://github.com/sdkgen/sdkgen/issues/176)
